### ISSUE TITLE
Inconsistent/incorrect XMI documentation

### ISSUE THREAD

**Issue by glirellus** [cimug-org/CIMTool#107]
The page at https://cimtool.ucaiug.io/how-to/import-cim-uml/ gives instructions to export XMI using the wrong instructions that do not produce the correct results.

The page at https://github.com/cimug-org/CIMTool does contain the correct XMI export instructions, which should be copied into the other page.

**Comment by tviegut** [comment]
@glirellus :  thanks for the heads up.  I actually noticed it a few days ago and corrected the docs / images.  I'm have it queued up to include in a pending pull requested.  If you catch anything else please let me know!!

**Comment by tviegut** [comment]
This has been fixed in both locations with the main README.md page now referring to the primary documentation for this topic.  This eliminates the dual maintenance.  Thanks @glirellus for the heads up.
