### ISSUE TITLE
CIMTool Project doesn't appear after creating new build

### ISSUE THREAD

**Issue by TheTimKiely** [CIMug-org/CIMTool#11]
Hi,
I'm new to CIMTool, so please pardon any obvious mistakes.
I followed the instructions for creating a development environment and packaging and deploying CIMTool.
I created a build from the "release-1.10.0.RC1" branch.
When I run the new CIMTool.exe, the CIMTool project type does not appear under the New/Project menu.  All that shows up in General/Project.
The error log indicates a problem with preference page:
```
!SESSION 2021-10-28 12:26:45.736 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.5.0_22
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -consoleLog

!ENTRY org.eclipse.ui 4 4 2021-10-28 12:27:19.880
!MESSAGE Invalid preference page path: XML Syntax
````

Any suggestions would really be appreciated.
Thanks,
Tim

**Comment by admin-cimug** [comment]
Tim,

I am closing this issue out as I am seeing both the "CIMTool Project" in both of the below scenarios.

Todd

![image](https://user-images.githubusercontent.com/63370413/173879948-bed946a1-0c06-4696-b057-3d0f0bbf7514.png)

![image](https://user-images.githubusercontent.com/63370413/173879638-26f9eb2d-7d52-44cb-8af1-d82a4ec97268.png)
