### ISSUE TITLE
Aggregation relationships are not appearing in the Profile Add/Remove tab

### ISSUE THREAD

**Issue by tviegut** [cimug-org/CIMTool#131]
### Discussed in https://github.com/cimug-org/CIMTool/discussions/129

<div type='discussions-op-text'>

<sup>Originally posted by **walterconcert** August  6, 2024</sup>
Hello everyone!
Is it expected that Aggregation relationship between classes doesn't appear in the Project Model view? Only association and generalization?
I have an .eap from customer that has some aggregations. As I prefer to work with CIMTool to build the profiles, it has becoming a problem for me.
</div>

**Comment by walterconcert** [comment]
Thanks @tviegut for opening the issue. 
I am using .eap directly as schema in my project. I tried optionally export to xmi, but unsucessfuly when reading in CIMTool.
Just a note: I am using EA 32bits, because the 64bits version is not working with output in .eap and .qea doesn't work in CIMTool, as far as I know.

**Comment by walterconcert** [comment]
To complement the title: Aggregation relationships are not appearing in the Project Model tab, as well.

**Comment by tviegut** [comment]
> To complement the title: Aggregation relationships are not appearing in the Project Model tab, as well.

My fix addresses this aspect as well @walterconcert :).  Also, support for EA16 `.qea`, `.qeax`, `.eapx` and `.feap` project file types  (i.e. https://github.com/cimug-org/CIMTool/issues/108 & https://github.com/cimug-org/CIMTool/issues/114) is implemented and tested and will be in the next release

**Comment by tviegut** [comment]
Hey @walterconcert , quick question.  How urgent is your need for this fix?

**Comment by walterconcert** [comment]
I have to deliver the profiles by end of August to the customer. I can edit the profiles using EA (personally I prefer to use CIMTool), so it is not so urgent, but it would be great having the fix in CIMTool so would avoid some overhead.

**Comment by admin-cimug** [comment]
@walterconcert , I'll go ahead then and push out a general release for you hopefully by EOD  or latest tomorrow. I tested this fix against '.XMI' and '.QEA'.  It should work as well for your '.EAP' files

**Comment by walterconcert** [comment]
Great news, @tviegut! Thanks a lot!

**Comment by admin-cimug** [comment]
@walterconcert : The release has been published.  Sorry for the delay.

**Comment by walterconcert** [comment]
Hi @tviegut !
I confess that I was not expecting even to have an answer so quickly in my post, as much a correction in the tool. So, no need to apologize :-).
I am very surprised and thankful.
I tested and it is okay!
Thanks a lot and congrats for maintain and share so powerfull tool!
