### ISSUE TITLE
Could not open the editor: org.eclipse.ui.PartInitException: Editor could not be initialized.

### ISSUE THREAD

**Issue by nlaws-camus** [CIMug-org/CIMTool#56]
When opening the XMI schema in [UCA-Part5-Profiles-1st-Edition](https://cimug.ucaiug.org/CIM%20Profiles/UCA-Part5-Profiles-1st-Edition-copyright.zip) I get:
<img width="942" alt="Screenshot 2022-11-14 at 1 22 56 PM" src="https://user-images.githubusercontent.com/110264418/201758500-cda25848-5bba-47ca-b0f3-3e3c51ef23f9.png">
maybe because I am on Windows Server 2012 R2 Datacenter?

**Comment by tviegut** [comment]
> When opening the XMI schema in [UCA-Part5-Profiles-1st-Edition](https://cimug.ucaiug.org/CIM%20Profiles/UCA-Part5-Profiles-1st-Edition-copyright.zip) I get:
> 
> <img width="942" alt="Screenshot 2022-11-14 at 1 22 56 PM" src="https://user-images.githubusercontent.com/110264418/201758500-cda25848-5bba-47ca-b0f3-3e3c51ef23f9.png">
> 
> maybe because I am on Windows Server 2012 R2 Datacenter?

- [ ] @nlaws-camus :  yes, that would be my first hunch. Also review the installation instructions for CIMTool that you are configured properly to use JRE or JDK 1.8.  Those instructions explain why and how.  See the README page for that link. If you check and find you are properly configured then try on standard windows.  Let us know how it goes.
